opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/public-release-reloaded/ecaml"
bug-reports: "https://github.com/public-release-reloaded/ecaml/issues"
dev-repo: "git+https://github.com/public-release-reloaded/ecaml.git#v0.18_preview.130.100+614+reloaded"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/ecaml/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.5.0"}
  "async" {>= "v0.18~" & < "v0.19~"}
  "async_kernel" {>= "v0.18~" & < "v0.19~"}
  "async_unix" {>= "v0.18~" & < "v0.19~"}
  "base" {>= "v0.18~" & < "v0.19~"}
  "core" {>= "v0.18~" & < "v0.19~"}
  "core_kernel" {>= "v0.18~" & < "v0.19~"}
  "core_unix" {>= "v0.18~" & < "v0.19~"}
  "expect_test_helpers_core" {>= "v0.18~" & < "v0.19~"}
  "file_path" {>= "v0.18~" & < "v0.19~"}
  "memtrace" {>= "v0.18~" & < "v0.19~"}
  "ppx_expect" {>= "v0.18~" & < "v0.19~"}
  "ppx_jane" {>= "v0.18~" & < "v0.19~"}
  "sexp_pretty" {>= "v0.18~" & < "v0.19~"}
  "sexplib" {>= "v0.18~" & < "v0.19~"}
  "dune" {>= "3.17.0"}
  "uutf" {>= "1.0.2"}
]
available: arch != "x86_32"
synopsis: "Library for writing Emacs plugin in OCaml"
description: "
Ecaml is a library for writing Emacs plugins in OCaml. It uses Emacs
25 support for plugins to load native OCaml compiled code.
"
